chore: Add push to OCP bundle in CI
Mellanox/network-operator pull request #1221
Opened 2024-12-24 13:26 UTC by dahalperin

- push ocp-bundle on every merge
- tag format is short sha commit

2024-12-25 07:05 UTC, rollandf approved these changes

2024-12-30 11:41 UTC, e0ne requested changes

2024-12-30 11:41 UTC, e0ne commented on .github/workflows/ci.yaml
> +          export DEFAULT_CHANNEL=v1.1 # hard coded
it should be:
export DEFAULT_CHANNEL=v1.1,$VERSION
export CHANNELS=stable,$VERSION

2025-01-02 10:31 UTC, rollandf commented on .github/workflows/ci.yaml
> +          export DEFAULT_CHANNEL=v1.1 # hard coded
I think the current code is OK.
According to [doc](https://github.com/Mellanox/network-operator/blob/master/docs/operator-bundle.md?plain=1#L14) the DEFAULT_CHANNEL is a single entry pointing to major-minor version

2025-01-06 20:07 UTC, e0ne approved these changes

2025-01-06 20:08 UTC, merged

2025-01-07 07:21 UTC, maze88 reviewed
What about the adjustments we discussed a couple weeks ago?

2025-01-07 07:34 UTC, rollandf commented on .github/workflows/ci.yaml
> +          export VERSION=1.1.0-${{ env.VERSION_WITH_PREFIX }}  # using the commit hash
These are the versions of the bundle/application
Since that here we are building on every commit, there is no `real` version. That's why they are hard coded.

2025-01-07 07:37 UTC, rollandf commented on .github/workflows/ci.yaml
> +          export CHANNELS=stable,v1.1 # hard coded
For future tests of upgrade in OCP, if a new version comes up in the stable channel, an upgrade should be performed automatically

2025-01-07 07:38 UTC, rollandf commented
> What about the adjustments we discussed a couple weeks ago?

@maze88 Did you comment on the PR and request changes there?

2025-01-07 08:37 UTC, rollandf commented
> > > What about the adjustments we discussed a couple weeks ago?
> > 
> > 
> > @maze88 Did you comment on the PR and request changes there?
> 
> No, Dana and I did a couple of sessions over MSteams.

I suggest to leave comments using GitHub so that everybody will be aware of them.