Add support for proxy and custom CA certificate for Openshift
Mellanox/network-operator pull request #378
Opened 2022-07-05 06:32 UTC by ykulazhenkov

The operator can read proxy settings and trusted CA bundle from Openshift cluster-wide Proxy object and configure OFED container to use them.
If NicClusterPolicy contains proxy or trusted CA settings they will take precedence over the cluster-wide proxy settings.

2022-07-05 14:39 UTC, e0ne requested changes

2022-07-05 14:39 UTC, e0ne commented on pkg/state/state_ofed_test.go
> +Copyright 2022 NVIDIA
Please, change it to:
 # 2022 NVIDIA CORPORATION & AFFILIATES

2022-07-07 10:39 UTC, ykulazhenkov commented on pkg/state/state_ofed.go
> +	envVarNameHTTPProxy  = "HTTP_PROXY"
I think it is more about personal preference, for me upper-case looks more like env variable name. In the code we check and set values in both cases.

2022-07-07 10:40 UTC, ykulazhenkov commented on pkg/state/state_ofed.go
> +func (s *stateOFED) createConfigMapVolumeMounts(namespace, configMapName, destinationDir string,
we don't path this field as argument anymore

2022-07-07 10:41 UTC, ykulazhenkov commented on pkg/state/state_ofed.go
> +	destinationPathOverride map[string]string) (
I changed override logic to be more explicit. Now we have static map with overrides, please, check latest code changes and share your opinion.

2022-07-07 10:47 UTC, ykulazhenkov commented on pkg/state/state_ofed.go
> +func (s *stateOFED) setEnvFromClusterWideProxy(cr *mellanoxv1alpha1.NicClusterPolicy, proxyConfig *osconfigv1.Proxy) {
done

2022-07-07 10:49 UTC, ykulazhenkov commented on pkg/state/state_ofed.go
> +	proxiesParams := [][]string{
I use this construction because we need to preserve variables order,  I added the comment to clarify

2022-07-07 10:56 UTC, ykulazhenkov commented on pkg/state/state_ofed.go
> +			log.V(consts.LogLevelWarning).Info("TrustedCAConfigMap has empty ca-bundle.crt key",
I would say that openshift operates incorrectly for some reason.

2022-07-07 10:56 UTC, ykulazhenkov commented on pkg/state/state_ofed.go
> +		osTrustedCAConfigMap, err := s.getOrCreateTrustedCAConfigMap(cr, clusterWideProxyConfig)
I moved this logic to the `Sync` function

2022-07-07 14:23 UTC, ykulazhenkov commented on pkg/state/state_ofed.go
> +	// read ClusterWide Proxy configuration for Openshift
discussed offline: decided not to introduce such value to reduce deployment complexity on different platforms.

2022-07-08 08:14 UTC, ykulazhenkov commented
@e0ne PTAL

2022-07-08 08:22 UTC, ykulazhenkov commented
/retest-image_scan

2022-07-08 09:43 UTC, ykulazhenkov commented
/retest-image_scan

2022-07-08 09:44 UTC, ykulazhenkov commented
/retest-image_scan

2022-07-08 10:45 UTC, e0ne approved these changes

2022-07-08 10:46 UTC, merged