Add support for CDI in k8s-rdma-shared-dev-plugin deployments
Mellanox/network-operator pull request #584
Opened 2023-08-07 06:42 UTC by almaslennikov

Almost the same with **https://github.com/Mellanox/network-operator/pull/565**. Whichever is merged last needs to merge into the existing one

2023-08-17 06:23 UTC, almaslennikov commented
/retest-all

2023-09-26 08:42 UTC, e0ne requested changes
Please, update k8s-rdma-shared-dev-plugin version to the latest build `fe7f371c7e1b8315bf900f71cd25cfc1251dc775`

2023-09-26 12:19 UTC, abdallahyas commented
CIs are unable to find the image, are you sure it exists?

2023-09-26 13:07 UTC, e0ne requested changes

2023-09-26 13:07 UTC, e0ne commented on deployment/network-operator/values.yaml
> +  version: fe7f371c7e1b8315bf900f71cd25cfc1251dc775
it should be `sha-fe7f371c7e1b8315bf900f71cd25cfc1251dc775`

2023-09-26 19:54 UTC, e0ne approved these changes

2023-09-26 19:54 UTC, merged